// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: schema/notifications.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Notification_Type int32

const (
	Notification_SUCCESS     Notification_Type = 0
	Notification_INFORMATION Notification_Type = 1
	Notification_WARNING     Notification_Type = 2
	Notification_ERROR       Notification_Type = 3
)

// Enum value maps for Notification_Type.
var (
	Notification_Type_name = map[int32]string{
		0: "SUCCESS",
		1: "INFORMATION",
		2: "WARNING",
		3: "ERROR",
	}
	Notification_Type_value = map[string]int32{
		"SUCCESS":     0,
		"INFORMATION": 1,
		"WARNING":     2,
		"ERROR":       3,
	}
)

func (x Notification_Type) Enum() *Notification_Type {
	p := new(Notification_Type)
	*p = x
	return p
}

func (x Notification_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Notification_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_notifications_proto_enumTypes[0].Descriptor()
}

func (Notification_Type) Type() protoreflect.EnumType {
	return &file_schema_notifications_proto_enumTypes[0]
}

func (x Notification_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Notification_Type.Descriptor instead.
func (Notification_Type) EnumDescriptor() ([]byte, []int) {
	return file_schema_notifications_proto_rawDescGZIP(), []int{0, 0}
}

type Notification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    Notification_Type      `protobuf:"varint,1,opt,name=type,proto3,enum=notifications.Notification_Type" json:"type,omitempty"`
	Action  *Notification_Action   `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Created *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	User    *User                  `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *Notification) Reset() {
	*x = Notification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_notifications_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_schema_notifications_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_schema_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetType() Notification_Type {
	if x != nil {
		return x.Type
	}
	return Notification_SUCCESS
}

func (x *Notification) GetAction() *Notification_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *Notification) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *Notification) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type Notification_Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Action:
	//
	//	*Notification_Action_ValidateUser_
	Action isNotification_Action_Action `protobuf_oneof:"action"`
}

func (x *Notification_Action) Reset() {
	*x = Notification_Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_notifications_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notification_Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification_Action) ProtoMessage() {}

func (x *Notification_Action) ProtoReflect() protoreflect.Message {
	mi := &file_schema_notifications_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification_Action.ProtoReflect.Descriptor instead.
func (*Notification_Action) Descriptor() ([]byte, []int) {
	return file_schema_notifications_proto_rawDescGZIP(), []int{0, 0}
}

func (m *Notification_Action) GetAction() isNotification_Action_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *Notification_Action) GetValidateUser() *Notification_Action_ValidateUser {
	if x, ok := x.GetAction().(*Notification_Action_ValidateUser_); ok {
		return x.ValidateUser
	}
	return nil
}

type isNotification_Action_Action interface {
	isNotification_Action_Action()
}

type Notification_Action_ValidateUser_ struct {
	ValidateUser *Notification_Action_ValidateUser `protobuf:"bytes,1,opt,name=validate_user,json=validateUser,proto3,oneof"`
}

func (*Notification_Action_ValidateUser_) isNotification_Action_Action() {}

type Notification_Action_ValidateUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Notification_Action_ValidateUser) Reset() {
	*x = Notification_Action_ValidateUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_notifications_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notification_Action_ValidateUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification_Action_ValidateUser) ProtoMessage() {}

func (x *Notification_Action_ValidateUser) ProtoReflect() protoreflect.Message {
	mi := &file_schema_notifications_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification_Action_ValidateUser.ProtoReflect.Descriptor instead.
func (*Notification_Action_ValidateUser) Descriptor() ([]byte, []int) {
	return file_schema_notifications_proto_rawDescGZIP(), []int{0, 0, 0}
}

var File_schema_notifications_proto protoreflect.FileDescriptor

var file_schema_notifications_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x73, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x91, 0x03, 0x0a, 0x0c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x34, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x20, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x3a, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x1a, 0x7a, 0x0a, 0x06, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x56, 0x0a, 0x0d, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x6e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0c,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x1a, 0x0e, 0x0a, 0x0c,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x42, 0x08, 0x0a, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3c, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x49,
	0x4e, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07,
	0x57, 0x41, 0x52, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x03, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x63, 0x61, 0x6c, 0x65, 0x6e, 0x64, 0x61, 0x72, 0x2d, 0x6d, 0x65, 0x2f, 0x63,
	0x6f, 0x72, 0x65, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schema_notifications_proto_rawDescOnce sync.Once
	file_schema_notifications_proto_rawDescData = file_schema_notifications_proto_rawDesc
)

func file_schema_notifications_proto_rawDescGZIP() []byte {
	file_schema_notifications_proto_rawDescOnce.Do(func() {
		file_schema_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(file_schema_notifications_proto_rawDescData)
	})
	return file_schema_notifications_proto_rawDescData
}

var file_schema_notifications_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_schema_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_schema_notifications_proto_goTypes = []interface{}{
	(Notification_Type)(0),                   // 0: notifications.Notification.Type
	(*Notification)(nil),                     // 1: notifications.Notification
	(*Notification_Action)(nil),              // 2: notifications.Notification.Action
	(*Notification_Action_ValidateUser)(nil), // 3: notifications.Notification.Action.ValidateUser
	(*timestamppb.Timestamp)(nil),            // 4: google.protobuf.Timestamp
	(*User)(nil),                             // 5: users.User
}
var file_schema_notifications_proto_depIdxs = []int32{
	0, // 0: notifications.Notification.type:type_name -> notifications.Notification.Type
	2, // 1: notifications.Notification.action:type_name -> notifications.Notification.Action
	4, // 2: notifications.Notification.created:type_name -> google.protobuf.Timestamp
	5, // 3: notifications.Notification.user:type_name -> users.User
	3, // 4: notifications.Notification.Action.validate_user:type_name -> notifications.Notification.Action.ValidateUser
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_schema_notifications_proto_init() }
func file_schema_notifications_proto_init() {
	if File_schema_notifications_proto != nil {
		return
	}
	file_schema_users_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_schema_notifications_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_notifications_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notification_Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_notifications_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notification_Action_ValidateUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_schema_notifications_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Notification_Action_ValidateUser_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schema_notifications_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_notifications_proto_goTypes,
		DependencyIndexes: file_schema_notifications_proto_depIdxs,
		EnumInfos:         file_schema_notifications_proto_enumTypes,
		MessageInfos:      file_schema_notifications_proto_msgTypes,
	}.Build()
	File_schema_notifications_proto = out.File
	file_schema_notifications_proto_rawDesc = nil
	file_schema_notifications_proto_goTypes = nil
	file_schema_notifications_proto_depIdxs = nil
}
