// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: booking/v1/slot.proto

package bookingv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	businessv1 "github.com/calendar-me/core/domain/business/v1"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = businessv1.Availability_Type(0)
)

// Validate checks the field values on Slot with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Slot) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Slot with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in SlotMultiError, or nil if none found.
func (m *Slot) ValidateAll() error {
	return m.validate(true)
}

func (m *Slot) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for Type

	if all {
		switch v := interface{}(m.GetStart()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SlotValidationError{
					field:  "Start",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SlotValidationError{
					field:  "Start",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStart()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SlotValidationError{
				field:  "Start",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetAvailability()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SlotValidationError{
					field:  "Availability",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SlotValidationError{
					field:  "Availability",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAvailability()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SlotValidationError{
				field:  "Availability",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SlotMultiError(errors)
	}

	return nil
}

// SlotMultiError is an error wrapping multiple validation errors returned by
// Slot.ValidateAll() if the designated constraints aren't met.
type SlotMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SlotMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SlotMultiError) AllErrors() []error { return m }

// SlotValidationError is the validation error returned by Slot.Validate if the
// designated constraints aren't met.
type SlotValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SlotValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SlotValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SlotValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SlotValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SlotValidationError) ErrorName() string { return "SlotValidationError" }

// Error satisfies the builtin error interface
func (e SlotValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSlot.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SlotValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SlotValidationError{}
