// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: user/v1/role.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role_Type int32

const (
	Role_TYPE_UNSPECIFIED Role_Type = 0
	Role_TYPE_ADMIN       Role_Type = 1
	Role_TYPE_EDITOR      Role_Type = 2
)

// Enum value maps for Role_Type.
var (
	Role_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_ADMIN",
		2: "TYPE_EDITOR",
	}
	Role_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_ADMIN":       1,
		"TYPE_EDITOR":      2,
	}
)

func (x Role_Type) Enum() *Role_Type {
	p := new(Role_Type)
	*p = x
	return p
}

func (x Role_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_user_v1_role_proto_enumTypes[0].Descriptor()
}

func (Role_Type) Type() protoreflect.EnumType {
	return &file_user_v1_role_proto_enumTypes[0]
}

func (x Role_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role_Type.Descriptor instead.
func (Role_Type) EnumDescriptor() ([]byte, []int) {
	return file_user_v1_role_proto_rawDescGZIP(), []int{0, 0}
}

type Role struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   Role_Type `protobuf:"varint,1,opt,name=type,proto3,enum=user.v1.Role_Type" json:"type,omitempty"`
	UserId string    `protobuf:"bytes,2,opt,name=user_id,proto3" json:"user_id,omitempty"`
	// Types that are assignable to Element:
	//
	//	*Role_BusinessId
	//	*Role_ServiceId
	Element isRole_Element `protobuf_oneof:"element"`
}

func (x *Role) Reset() {
	*x = Role{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_v1_role_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_role_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_user_v1_role_proto_rawDescGZIP(), []int{0}
}

func (x *Role) GetType() Role_Type {
	if x != nil {
		return x.Type
	}
	return Role_TYPE_UNSPECIFIED
}

func (x *Role) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (m *Role) GetElement() isRole_Element {
	if m != nil {
		return m.Element
	}
	return nil
}

func (x *Role) GetBusinessId() string {
	if x, ok := x.GetElement().(*Role_BusinessId); ok {
		return x.BusinessId
	}
	return ""
}

func (x *Role) GetServiceId() string {
	if x, ok := x.GetElement().(*Role_ServiceId); ok {
		return x.ServiceId
	}
	return ""
}

type isRole_Element interface {
	isRole_Element()
}

type Role_BusinessId struct {
	BusinessId string `protobuf:"bytes,3,opt,name=business_id,proto3,oneof"`
}

type Role_ServiceId struct {
	ServiceId string `protobuf:"bytes,4,opt,name=service_id,proto3,oneof"`
}

func (*Role_BusinessId) isRole_Element() {}

func (*Role_ServiceId) isRole_Element() {}

var File_user_v1_role_proto protoreflect.FileDescriptor

var file_user_v1_role_proto_rawDesc = []byte{
	0x0a, 0x12, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0xd8, 0x01,
	0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x6f, 0x6c, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0b, 0x62, 0x75, 0x73, 0x69,
	0x6e, 0x65, 0x73, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x0b, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0a,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x22, 0x3d,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x44, 0x49, 0x54, 0x4f, 0x52, 0x10, 0x02, 0x42, 0x09, 0x0a,
	0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x88, 0x01, 0x0a, 0x0b, 0x63, 0x6f, 0x6d,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x42, 0x09, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x63, 0x61, 0x6c, 0x65, 0x6e, 0x64, 0x61, 0x72, 0x2d, 0x6d, 0x65, 0x2f, 0x63, 0x6f,
	0x72, 0x65, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x76,
	0x31, 0x3b, 0x75, 0x73, 0x65, 0x72, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x55, 0x58, 0x58, 0xaa, 0x02,
	0x07, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x07, 0x55, 0x73, 0x65, 0x72, 0x5c,
	0x56, 0x31, 0xe2, 0x02, 0x13, 0x55, 0x73, 0x65, 0x72, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x08, 0x55, 0x73, 0x65, 0x72, 0x3a,
	0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_v1_role_proto_rawDescOnce sync.Once
	file_user_v1_role_proto_rawDescData = file_user_v1_role_proto_rawDesc
)

func file_user_v1_role_proto_rawDescGZIP() []byte {
	file_user_v1_role_proto_rawDescOnce.Do(func() {
		file_user_v1_role_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_v1_role_proto_rawDescData)
	})
	return file_user_v1_role_proto_rawDescData
}

var file_user_v1_role_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_v1_role_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_user_v1_role_proto_goTypes = []interface{}{
	(Role_Type)(0), // 0: user.v1.Role.Type
	(*Role)(nil),   // 1: user.v1.Role
}
var file_user_v1_role_proto_depIdxs = []int32{
	0, // 0: user.v1.Role.type:type_name -> user.v1.Role.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_v1_role_proto_init() }
func file_user_v1_role_proto_init() {
	if File_user_v1_role_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_v1_role_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Role); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_user_v1_role_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Role_BusinessId)(nil),
		(*Role_ServiceId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_v1_role_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_v1_role_proto_goTypes,
		DependencyIndexes: file_user_v1_role_proto_depIdxs,
		EnumInfos:         file_user_v1_role_proto_enumTypes,
		MessageInfos:      file_user_v1_role_proto_msgTypes,
	}.Build()
	File_user_v1_role_proto = out.File
	file_user_v1_role_proto_rawDesc = nil
	file_user_v1_role_proto_goTypes = nil
	file_user_v1_role_proto_depIdxs = nil
}
